resolver: lts-17.6

packages:
  - "."

extra-deps:
  - purescript-0.14.5
  - purescript-cst-0.4.0.0
  - language-javascript-0.7.0.0

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
