resolver: lts-18.15
packages:
  - "."

extra-deps:
  - purescript-0.14.7
  - purescript-cst-0.5.0.0
  - language-javascript-0.7.0.0

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
