resolver: lts-18.15
packages:
  - "."

extra-deps:
  - purescript-0.15.2
  - language-javascript-0.7.0.0
  - monoidal-containers-0.6.2.0
  - process-1.6.13.1
  - Cabal-3.2.1.0

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
